"""post body character limit

Revision ID: 775b39c7df83
Revises: 834b1a697901
Create Date: 2020-03-09 16:09:34.217991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '775b39c7df83'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'body',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=140),
               type_=sa.String(length=1140),
               existing_nullable=True)
    op.alter_column('task', 'complete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'complete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('post', 'body',
               existing_type=sa.String(length=1140),
               type_=mysql.VARCHAR(collation='utf8_bin', length=140),
               existing_nullable=True)
    # ### end Alembic commands ###
